name: CI/CD - WSL Self-Hosted (Docker Compose)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, wsl, docker, test]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set VERSION env
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build image
        run: docker compose build --pull

      - name: Recreate container
        run: |
          docker compose down || true
          docker compose up -d

      - name: Health check
        run: |
          for i in {1..20}; do
            if curl -fsS http://localhost:8080 >/dev/null; then
              echo "OK"
              exit 0
            fi
            sleep 1
          done
          echo "App did not become healthy in time"
          docker compose logs --no-color
          exit 1
